# Generated by Django 2.2.13 on 2020-07-07 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200707_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 11, 32, 40, 895623), verbose_name='date published'),
        ),
    ]
